version: '3'
services:
  app:
    image: ghcr.io/ploutosdevs/ploutos:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: ploutos
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_TOKEN_TEST=${TELEGRAM_BOT_TOKEN_TEST}
    pull_policy: always