version: '3'
services:
  app:
    # image: ghcr.io/${GITHUB_REPOSITORY}:latest
    build:
      context: .
      dockerfile: DockerFile
    container_name: ploutos
    restart: always
    env_file:
      - .env