name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main # Adjust to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/ploutosdevs/ploutos:latest .
          docker push ghcr.io/ploutosdevs/ploutos:latest
      
      - name: Transfer files to Yandex Cloud VM
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.REMOTE_USER }}/app"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.7
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BOT_TOKEN_TEST: ${{ secrets.TELEGRAM_BOT_TOKEN_TEST }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            export TELEGRAM_BOT_TOKEN_TEST=${{ secrets.TELEGRAM_BOT_TOKEN_TEST }}
            cd /home/${{ secrets.REMOTE_USER }}/app
            docker-compose down
            docker-compose up -d --build